development: &default
  adapter: postgresql
  database: meme_weather_development
  host: localhost
  encoding: utf8
  min_messages: warning
  pool: 5
  timeout: 5000

test:
  <<: *default
  database: meme_weather_test<%= ENV['TEST_ENV_NUMBER'] %>

production:
  <<: *default
  database: meme_weather_production
