# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

default: &default
  devise_secret_key: <%= ENV["DEVISE_SECRET_KEY"] %>
  open_weather_app_id: <%= ENV["OPEN_WEATHER_APP_ID"] %>
  google_cse_api_key: <%= ENV["GOOGLE_CSE_API_KEY"] %>
  google_cse_cx: <%= ENV["GOOGLE_CSE_CX"] %>

development:
  <<: *default
  secret_key_base: 023b5c04ca3df7873f8dc15b0e8d1c88941b10e979cd5779dedf7e9d57d0fb563e90a82445209afaa4838a99571530806a9586f8146ee417dce87de3104bf348

test:
  <<: *default
  secret_key_base: 854bf73942965dd6160d1b72599b18880ef3204ebc22581e1cfe1cfb7f413e79ea8d5d2fab5ee51e519a7b0af54ab6c3b5fce73b5b8c1f8cc1f8d3ed4b112c2f

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  <<: *default
  mailgun_api_key: <%= ENV["MAILGUN_API_KEY"] %>
  mailgun_domain: <%= ENV["MAILGUN_DOMAIN"] %>
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>

